"""Align Game model with schema

Revision ID: 0bf590139095
Revises: 4e97bca88f64
Create Date: 2025-07-07 15:29:26.575644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0bf590139095'
down_revision: Union[str, Sequence[str], None] = '4e97bca88f64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    game_status_enum = postgresql.ENUM('IN_PROGRESS', 'COMPLETED', 'ABANDONED', name='gamestatus')
    game_status_enum.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'ABANDONED', name='gamestatus'), nullable=False))
    op.add_column('games', sa.Column('game_duration', sa.Integer(), nullable=True))
    op.drop_column('games', 'result')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('result', postgresql.ENUM('GOAT_WIN', 'TIGER_WIN', 'DRAW', 'ABORTED', name='gameresult'), autoincrement=False, nullable=True))
    op.drop_column('games', 'game_duration')
    op.drop_column('games', 'status')
    game_status_enum = postgresql.ENUM('IN_PROGRESS', 'COMPLETED', 'ABANDONED', name='gamestatus')
    game_status_enum.drop(op.get_bind())
    # ### end Alembic commands ###
