"""Update User model with status, role, country, and relationships

Revision ID: 225a78ec5d7a
Revises: 1931e0c7a19c
Create Date: 2025-07-07 15:13:27.856590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '225a78ec5d7a'
down_revision: Union[str, Sequence[str], None] = '1931e0c7a19c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    userstatus_enum = sa.Enum('OFFLINE', 'ONLINE', 'INGAME', name='userstatus')
    userstatus_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('users', sa.Column('status', userstatus_enum, nullable=True))
    op.execute("UPDATE users SET status = 'OFFLINE'")
    op.alter_column('users', 'status', nullable=False)

    op.add_column('users', sa.Column('country', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'MODERATOR'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'country')
    op.drop_column('users', 'status')
    userstatus_enum = sa.Enum('OFFLINE', 'ONLINE', 'INGAME', name='userstatus')
    userstatus_enum.drop(op.get_bind())
    # ### end Alembic commands ###
