"""Add friendship_id to Friendship model

Revision ID: 4e97bca88f64
Revises: 225a78ec5d7a
Create Date: 2025-07-07 15:24:03.879039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e97bca88f64'
down_revision: Union[str, Sequence[str], None] = '225a78ec5d7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friendships', sa.Column('friendship_id', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('friendships', 'friendship_id')
    # ### end Alembic commands ###
