"""Align Tournament model with schema

Revision ID: 56385d65ed0c
Revises: ca30cba34376
Create Date: 2025-07-07 15:37:21.667333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56385d65ed0c'
down_revision: Union[str, Sequence[str], None] = 'ca30cba34376'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('description', sa.String(), nullable=True))
    op.add_column('tournaments', sa.Column('max_participants', sa.Integer(), nullable=False))
    op.add_column('tournaments', sa.Column('start_date', sa.DateTime(), nullable=False))
    op.add_column('tournaments', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.add_column('tournaments', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('tournaments', 'end_time')
    op.drop_column('tournaments', 'start_time')
    op.drop_column('tournaments', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('type', postgresql.ENUM('KNOCKOUT', 'ROUND_ROBIN', name='tournamenttype'), autoincrement=False, nullable=False))
    op.add_column('tournaments', sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('tournaments', sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('tournaments', 'created_at')
    op.drop_column('tournaments', 'end_date')
    op.drop_column('tournaments', 'start_date')
    op.drop_column('tournaments', 'max_participants')
    op.drop_column('tournaments', 'description')
    # ### end Alembic commands ###
