"""Align AIGame model with schema

Revision ID: 5e04f4d2b120
Revises: f1ba398e8df8
Create Date: 2025-07-07 15:45:28.415624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e04f4d2b120'
down_revision: Union[str, Sequence[str], None] = 'f1ba398e8df8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    aigamestatus = postgresql.ENUM('IN_PROGRESS', 'COMPLETED', name='aigamestatus')
    aigamestatus.create(op.get_bind())
    op.add_column('ai_games', sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', name='aigamestatus'), nullable=False))
    op.add_column('ai_games', sa.Column('winner', sa.String(), nullable=True))
    op.add_column('ai_games', sa.Column('game_duration', sa.Integer(), nullable=True))
    op.drop_column('ai_games', 'ended_at')
    op.drop_column('ai_games', 'result')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_games', sa.Column('result', postgresql.ENUM('WIN', 'LOSS', 'DRAW', name='aigameresult'), autoincrement=False, nullable=True))
    op.add_column('ai_games', sa.Column('ended_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('ai_games', 'game_duration')
    op.drop_column('ai_games', 'winner')
    op.drop_column('ai_games', 'status')
    aigamestatus = postgresql.ENUM('IN_PROGRESS', 'COMPLETED', name='aigamestatus')
    aigamestatus.drop(op.get_bind())
    # ### end Alembic commands ###
