"""Add host_side to Room model

Revision ID: 711922e77066
Revises: 8ac5e2bb95d1
Create Date: 2025-07-05 17:49:12.859309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '711922e77066'
down_revision: Union[str, Sequence[str], None] = '8ac5e2bb95d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('host_side', sa.String(), nullable=True))
    op.alter_column('rooms', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('rooms', 'status',
               existing_type=postgresql.ENUM('WAITING', 'PLAYING', 'FINISHED', name='roomstatus'),
               nullable=True)
    op.alter_column('rooms', 'host_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_rooms_name'), 'rooms', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rooms_name'), table_name='rooms')
    op.alter_column('rooms', 'host_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('rooms', 'status',
               existing_type=postgresql.ENUM('WAITING', 'PLAYING', 'FINISHED', name='roomstatus'),
               nullable=False)
    op.alter_column('rooms', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('rooms', 'host_side')
    # ### end Alembic commands ###
