"""fix_rating_history_schema

Revision ID: 728fefcbd092
Revises: e7888b6e1a66
Create Date: 2025-07-07 16:11:06.401587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '728fefcbd092'
down_revision: Union[str, Sequence[str], None] = 'e7888b6e1a66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings_history', sa.Column('id', sa.UUID(), nullable=False))
    op.add_column('ratings_history', sa.Column('game_id', sa.UUID(), nullable=False))
    op.add_column('ratings_history', sa.Column('rating_before', sa.Integer(), nullable=False))
    op.add_column('ratings_history', sa.Column('rating_after', sa.Integer(), nullable=False))
    op.add_column('ratings_history', sa.Column('changed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'ratings_history', 'games', ['game_id'], ['game_id'])
    op.drop_column('ratings_history', 'rating_change')
    op.drop_column('ratings_history', 'date')
    op.drop_column('ratings_history', 'rating_history_id')
    op.drop_column('ratings_history', 'new_rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings_history', sa.Column('new_rating', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('ratings_history', sa.Column('rating_history_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('ratings_history', sa.Column('date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('ratings_history', sa.Column('rating_change', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ratings_history', type_='foreignkey')
    op.drop_column('ratings_history', 'changed_at')
    op.drop_column('ratings_history', 'rating_after')
    op.drop_column('ratings_history', 'rating_before')
    op.drop_column('ratings_history', 'game_id')
    op.drop_column('ratings_history', 'id')
    # ### end Alembic commands ###
