"""Add room model

Revision ID: 8ac5e2bb95d1
Revises: a3b9eb1e707c
Create Date: 2025-07-05 17:13:51.247338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ac5e2bb95d1'
down_revision: Union[str, Sequence[str], None] = 'a3b9eb1e707c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('WAITING', 'PLAYING', 'FINISHED', name='roomstatus'), nullable=False),
    sa.Column('host_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('room_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_room_code'), 'rooms', ['room_code'], unique=True)
    op.create_table('room_players',
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('room_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_players')
    op.drop_index(op.f('ix_rooms_room_code'), table_name='rooms')
    op.drop_table('rooms')
    # ### end Alembic commands ###
