"""Add game_id to Room model

Revision ID: b90396c22524
Revises: 711922e77066
Create Date: 2025-07-05 18:09:39.141789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b90396c22524'
down_revision: Union[str, Sequence[str], None] = '711922e77066'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('game_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'rooms', 'games', ['game_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_column('rooms', 'game_id')
    # ### end Alembic commands ###
