"""Align Move model with schema

Revision ID: ca30cba34376
Revises: 0bf590139095
Create Date: 2025-07-07 15:32:09.977557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca30cba34376'
down_revision: Union[str, Sequence[str], None] = '0bf590139095'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moves', sa.Column('from_row', sa.Integer(), nullable=True))
    op.add_column('moves', sa.Column('from_col', sa.Integer(), nullable=True))
    op.add_column('moves', sa.Column('to_row', sa.Integer(), nullable=False))
    op.add_column('moves', sa.Column('to_col', sa.Integer(), nullable=False))
    op.drop_column('moves', 'from_pos')
    op.drop_column('moves', 'to_pos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moves', sa.Column('to_pos', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('moves', sa.Column('from_pos', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('moves', 'to_col')
    op.drop_column('moves', 'to_row')
    op.drop_column('moves', 'from_col')
    op.drop_column('moves', 'from_row')
    # ### end Alembic commands ###
