"""Align Tournament model with schema again

Revision ID: f1ba398e8df8
Revises: 56385d65ed0c
Create Date: 2025-07-07 15:42:40.698233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1ba398e8df8'
down_revision: Union[str, Sequence[str], None] = '56385d65ed0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('tournament_type', sa.Enum('ROUND_ROBIN', 'KNOCKOUT', name='tournamenttype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'tournament_type')
    # ### end Alembic commands ###
