export const colors = {
  light: {
    primary: '#C62828',
    onPrimary: '#FFFFFF',
    primaryContainer: '#FFCDD2',
    onPrimaryContainer: '#8C1F1F',
    secondary: '#795548',
    onSecondary: '#FFFFFF',
    secondaryContainer: '#EFEBE9',
    onSecondaryContainer: '#3E2723',
    tertiary: '#FF6F00',
    onTertiary: '#FFFFFF',
    tertiaryContainer: '#FFE0B2',
    onTertiaryContainer: '#E65100',
    surface: '#FAFAFA',
    onSurface: '#212121',
    surfaceVariant: '#F5F5F5',
    onSurfaceVariant: '#424242',
    outline: '#757575',
    outlineVariant: '#BDBDBD',
    background: '#FFFFFF',
    onBackground: '#212121',
    // Game-specific colors
    tigerColor: '#FF5722',
    goatColor: '#8BC34A',
    boardColor: '#8D6E63',
    highlightColor: '#FFC107',
    validMoveColor: '#4CAF50',
    attackColor: '#F44336',
  },
  dark: {
    primary: '#FF6F00',
    onPrimary: '#000000',
    primaryContainer: '#C62828',
    onPrimaryContainer: '#FFCDD2',
    secondary: '#A1887F',
    onSecondary: '#000000',
    secondaryContainer: '#5D4037',
    onSecondaryContainer: '#EFEBE9',
    tertiary: '#FFB74D',
    onTertiary: '#000000',
    tertiaryContainer: '#FF8F00',
    onTertiaryContainer: '#FFE0B2',
    surface: '#1E1E1E',
    onSurface: '#FFFFFF',
    surfaceVariant: '#2C2C2C',
    onSurfaceVariant: '#9E9E9E',
    outline: '#424242',
    outlineVariant: '#424242',
    background: '#121212',
    onBackground: '#FFFFFF',
    card: '#1E1E1E',
    text: '#FFFFFF',
    border: '#272727',
    notification: '#FF8F00',
    // Game-specific colors
    tigerColor: '#FF6F00',
    goatColor: '#4CAF50',
    boardColor: '#6D4C41',
    highlightColor: '#FFD54F',
    validMoveColor: '#66BB6A',
    attackColor: '#F44336',
    // Semantic colors
    player1: '#FF6F00', // Tiger
    player2: '#4CAF50', // Goat
    validMove: '#66BB6A',
    attack: '#F44336',
    success: '#4CAF50',
    error: '#F44336',
  },
};

export const theme = {
  colors: colors.dark,
  fonts: {
    displayLarge: { fontSize: 57, fontWeight: '400' as const },
    displayMedium: { fontSize: 45, fontWeight: '400' as const },
    displaySmall: { fontSize: 36, fontWeight: '400' as const },
    headlineLarge: { fontSize: 32, fontWeight: '400' as const },
    headlineMedium: { fontSize: 28, fontWeight: '400' as const },
    headlineSmall: { fontSize: 24, fontWeight: '400' as const },
    titleLarge: { fontSize: 22, fontWeight: '500' as const },
    titleMedium: { fontSize: 16, fontWeight: '500' as const },
    titleSmall: { fontSize: 14, fontWeight: '500' as const },
    labelLarge: { fontSize: 14, fontWeight: '500' as const },
    labelMedium: { fontSize: 12, fontWeight: '500' as const },
    labelSmall: { fontSize: 11, fontWeight: '500' as const },
    bodyLarge: { fontSize: 16, fontWeight: '400' as const },
    bodyMedium: { fontSize: 14, fontWeight: '400' as const },
    bodySmall: { fontSize: 12, fontWeight: '400' as const },
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
  borderRadius: {
    sm: 4,
    md: 8,
    lg: 12,
    xl: 16,
  },
  gameBoard: {
    size: 5,
    cellSize: 60,
    lineWidth: 2,
    pieceSize: 50,
    padding: 20,
  },
};

export type Theme = typeof theme; 